### ISSUE TITLE
Siri feature checklist

### ISSUE THREAD

**Issue by tom-leamon** [AVsync-LIVE/Lexi#167]
Create issues for each of the following:
- [ ] Web search capabilities
- [ ] Set reminders and alarms
- [ ] Send messages and make phone calls
- [ ] Set timers and create to-do lists
- [ ] Music playback control
- [ ] GPS and location-based services
- [ ] Translation services
- [ ] Home automation and smart home device control
- [ ] Open apps and perform basic functions
- [ ] Restaurant recommendations and reservation assistance
- [ ] Sports updates and scores
- [ ] Weather forecasts and current conditions
- [ ] Traffic updates and directions
- [ ] Stock market updates
- [ ] Movie recommendations and showtimes
- [ ] Calendar scheduling and management
- [ ] Quick access to settings and device preferences.
